// Mocks generated by Mockito 5.4.6 from annotations
// in git_hub_contribution_app/test/features/github_contribution/domain/usecases/get_user_contributions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:git_hub_contribution_app/core/error/failures.dart' as _i5;
import 'package:git_hub_contribution_app/features/github_contribution/domain/entities/contribution.dart'
    as _i8;
import 'package:git_hub_contribution_app/features/github_contribution/domain/entities/user.dart'
    as _i6;
import 'package:git_hub_contribution_app/features/github_contribution/domain/repositories/github_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GithubRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGithubRepository extends _i1.Mock implements _i2.GithubRepository {
  MockGithubRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> getAuthenticatedUser(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthenticatedUser, [token]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#getAuthenticatedUser, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, bool>> validateToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validateToken, [token]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, bool>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, bool>>(
                this,
                Invocation.method(#validateToken, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.Contribution>>> getContributions(
    String? token,
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContributions, [token, year]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.Contribution>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.Contribution>>
                  >(this, Invocation.method(#getContributions, [token, year])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.Contribution>>>);

  @override
  _i3.Future<DateTime?> getLastUpdated(int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getLastUpdated, [year]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.Contribution>>>
  getCachedContributions(int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedContributions, [year]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.Contribution>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.Contribution>>
                  >(this, Invocation.method(#getCachedContributions, [year])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.Contribution>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.User>> getUser(
    String? token,
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [token, username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.User>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, _i6.User>>(
                this,
                Invocation.method(#getUser, [token, username]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.User>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.Contribution>>>
  getUserContributions(String? token, String? username, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getUserContributions, [token, username, year]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.Contribution>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.Contribution>>
                  >(
                    this,
                    Invocation.method(#getUserContributions, [
                      token,
                      username,
                      year,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.Contribution>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.User>>> getFollowingUsers(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowingUsers, [token]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.User>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.User>>>(
                    this,
                    Invocation.method(#getFollowingUsers, [token]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.User>>>);
}
